server.port=8082
spring.application.name=order-service
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
product.service.url=http://localhost:8081
shipping.free.threshold=1000
shipping.cost=50
order.shipping.full-fill-price = 1000.0
order.shipping.full-fill-discount = 50.0